# Generated by Django 5.1.6 on 2026-03-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True)),
                ('body_type', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('raw', 'RAW')], default='json', max_length=10)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_templates', to='core.environment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='api_client.apirequesttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True)),
                ('body_type', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('raw', 'RAW')], default='json', max_length=10)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('total_requests', models.PositiveIntegerField(default=10)),
                ('concurrency', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('single', 'Single Thread'), ('multi', 'Multi Thread')], default='single', max_length=10)),
                ('delay_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_scenarios', to='core.environment')),
                ('request_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_scenarios', to='api_client.apirequesttemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoadTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=15)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('concurrency', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('single', 'Single Thread'), ('multi', 'Multi Thread')], default='single', max_length=10)),
                ('delay_ms', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('min_ms', models.FloatField(blank=True, null=True)),
                ('max_ms', models.FloatField(blank=True, null=True)),
                ('avg_ms', models.FloatField(blank=True, null=True)),
                ('p95_ms', models.FloatField(blank=True, null=True)),
                ('p99_ms', models.FloatField(blank=True, null=True)),
                ('total_duration_ms', models.FloatField(blank=True, null=True)),
                ('requests_per_second', models.FloatField(blank=True, null=True)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_runs', to='core.environment')),
                ('request_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_runs', to='api_client.apirequesttemplate')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='api_client.loadtestscenario')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
